### ISSUE TITLE
USB_LP_CAN1_RX0_IRQHandler在USBDevice与ebox_can中多重定义问题

### ISSUE THREAD

**Issue by ReviewClouds** [eboxmaker/eBox_Framework#10]
component\usb_device_stack\USBDevice\USBHAL_STM32F1.cpp中函数USB_LP_CAN1_RX0_IRQHandler（） 与 
ebox\hardware\cortex-m3\Peripherals\ebox_can.cpp中USB_LP_CAN1_RX0_IRQHandler（）函数会形成多重定义，怎么解决？

**Comment by eboxmaker** [comment]
如果不用can的话就把他从工程中移除

**Comment by ReviewClouds** [comment]
好了移除了，主要问题是你USBDevice目录下还有一个.c文件没有添加到工程中，谢谢
