### ISSUE TITLE
USB  HID 异常

### ISSUE THREAD

**Issue by ReviewClouds** [eboxmaker/eBox_Framework#11]
想用USB HID来实现stm32的USB设备功能，现用到源程序中USBDevice.cpp文件，函数void USBDevice::connect(bool blocking)中是不是一直在阻塞，因为你的configured（）函数
返回的一直是非0？？是这样吗

**Comment by ReviewClouds** [comment]
之前我引脚配置问题

**Comment by quanmao** [comment]
建议你加QQ群沟通，更及时有效一些 139218853
