### ISSUE TITLE
 可以继承Arduino的Stream库

### ISSUE THREAD

**Issue by FASTSHIFT** [eboxmaker/eBox_Framework#7]
继承Stream可以获得更好的流式操作，比如String s = usart1.readString()

**Comment by eboxmaker** [comment]
这个库我之前看过的。这种机制是建立在串口使用环形缓冲区接受数据的基础上，限制了串口等设备的灵活性。而且还是一种阻塞性的操作。用户很可能忽略这一点导致主循环阻塞，引起不必要的麻烦。

**Comment by FASTSHIFT** [comment]
@eboxmaker SD库的文件系统也继承了

**Comment by eboxmaker** [comment]
我已经加进来了

**Comment by eboxmaker** [comment]
最新的代码在不影响之前模式的情况下增加了UartStream的类。支持了你所说的功能
